# Generated by Django 3.2.5 on 2022-02-02 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220202_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Email',
            new_name='Emaill',
        ),
    ]
