# Generated by Django 3.2.5 on 2022-02-03 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_imagedata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imagedata',
            new_name='Imgdata',
        ),
    ]
