# Generated by Django 3.2.5 on 2022-02-03 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220203_1642'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imgsdata',
        ),
    ]
