# Generated by Django 3.2.5 on 2022-02-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_imgsdata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgsdata',
            name='Image',
            field=models.ImageField(upload_to='app/img/'),
        ),
    ]
